[versions]
agp = "9.0.0"
android-desugar = "2.1.5"
androidx-annotation = "1.9.1"
androidx-core = "1.17.0"
androidx-test-rules = "1.7.0"
androidx-test-runner = "1.7.0"
dokka = "2.1.0"
ezvcard = "0.12.1"
guava = "33.5.0-android"
# noinspection NewerVersionAvailable
ical4j = "3.2.19"   # final version; update to 4.x will require much work
junit = "4.13.2"
kotlin = "2.2.21"
mockk = "1.14.7"
roboelectric = "4.16"
slf4j = "2.0.17"
spotbugs = "4.9.8"

[libraries]
android-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "android-desugar" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
ezvcard = { module = "com.googlecode.ez-vcard:ez-vcard", version.ref = "ezvcard" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
ical4j = { module = "org.mnode.ical4j:ical4j", version.ref = "ical4j" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
roboelectric = { module = "org.robolectric:robolectric", version.ref = "roboelectric" }
slf4j-jdk = { module = "org.slf4j:slf4j-jdk14", version.ref = "slf4j" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }